<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
def matrix_mul(a,b):

  #shape of Mat_1
  row1=len(a)
  col1=len(a[0])

  #shape of Mat_2
  row2=len(b)
  col2=len(b[0])

    #if condition for matrix multiplication is True
  if col1==row2:
    result = [[0 for x in range(col2)] for y in range(row1)]
    for i in range (row1):
      for j in range (col2):
        for k in range(row2):
          result[i][j] += a[i][k] * b[k][j] 
          
    return result

    #if condition for matrix multiplication is False
  else:
    print("Matrix Multiplication is not Possible")

a  = [[1 ,2],
      [3 ,4]]
b   = [[1 ,2, 3, 4, 5],
      [5 ,6 ,7, 8, 9]]      
     
matrix_mul(a,b) 

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]

<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [14]:
from random import uniform

a = [0, 5 ,27 ,6 ,13, 28 ,100, 45 ,10 ,79]

def pick_a_number_from_list(a):
    p=uniform(0,1)
    s=sum(a)

    #calculating weightage of each number in list
    prop = []
    for i in range(len(a)):
        prop.append(a[i]/s)
        # print(prop)

    #cumulative sum of proportions
    c=[]
    for i in range(0,len(a)):
        c.append(sum(prop[0:(i+1)]))

    #number extracter as per uniform probablity
    for j in range(0,len(a)):
        if p<=c[j]:
            number=a[j]
            return number
    
def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(a)
        print(number)

sampling_based_on_magnitued()

100
79
100
45
79
100
6
100
79
27
45
79
79
27
79
45
79
79
27
79
100
45
45
13
79
79
45
100
79
45
5
27
45
27
27
13
28
28
100
79
79
79
28
100
79
100
28
100
5
45
100
79
27
27
45
100
79
100
79
13
5
27
100
10
79
27
79
28
79
45
5
79
100
45
100
45
79
45
27
45
79
13
13
100
79
79
100
79
79
100
79
100
13
45
79
27
100
28
79


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [20]:
import re

def replace_digits(string):
    lst=[]
    for ele in string:
        if ele.isdigit():
            lst.append('#')
    ans=''.join(lst)
    return ans

String=input('Enter the string= ')

replace_digits(String)

Enter the string= #2a$#b%c%561#


'####'

<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students

<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [16]:
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10']
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80]

def display_dash_board(students, marks):

  #creating list of tuples(student,marks)
  ziplist = list(zip(students,marks))

  #top_5_max
  ziplist.sort(key = lambda x:x[1],reverse=True)
  print('\na.')
  for i,j in ziplist[:-5]:
    print(i,j)

  #top_5_min
  ziplist.sort(key = lambda x:x[1],reverse=False)
  print('\nb.')
  for i,j in ziplist[:-5]:
    print(i,j)

  #Students within_25_and_75
  print('\nc.')

  #Calculating 25th and 75th percentile marks
  mx = max(Marks)
  mn = min(Marks)

  diff = mx - mn

  per_25 = diff*0.25
  per_75 = diff*0.75

  for i,j in ziplist:
    if j < per_75 and j > per_25:
      print(i,j)

display_dash_board(Students, Marks)


a.
student8 98
student10 80
student2 78
student5 48
student1 45

b.
student3 12
student4 14
student9 35
student6 43
student1 45

c.
student9 35
student6 43
student1 45
student7 45
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [ ]:
from math import *
S = [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P = (3,-4)

#we have to calculate ditance from all points in S from P
def closest_points_to_p(S, P):

  #Cosine Distance list
  distance = []
  for i in S:
    x = i[0]  #x_cordinate
    y = i[1]  #y_cordinate
    
    #cosine distance formula
    d = acos((x*P[0] + y*P[1]) / (sqrt(x**2 + y**2) * (sqrt(P[0]**2 + P[1]**2))))
    distance.append(d)

  #top_5 closest points
  ziplist = list(zip(S,distance)) 
    #sorting 
  ziplist.sort(key = lambda x:x[1],reverse=False)

  return ziplist

ziplist = closest_points_to_p(S,P)

for i,j in ziplist[:5]:
  print(i)

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

from math import *
import regex as re
def i_am_the_one(red,blue,line):

  x = re.findall('([\d\.+-]+)',line)
  #chnaging to INT type
  var = [float(i) for i in x ]

  #Cosine Distance list
  distance = []
  x = var[0]  #x_cordinate
  y = var[1]  #y_cordinate
  c = var[2]  #intercept

  #consider correct for RED = +1
  r =[]
  for p in Red:
    d = (x*p[0] + y*p[1] + c ) / (sqrt(x**2 + y**2)) * 1
    r.append(d) 

  #consider correct for Blue = -1
  b = []
  for p in Blue:
    d = (x*p[0] + y*p[1] + c ) / (sqrt(x**2 + y**2)) * (-1)
    b.append(d) 

  #combining RED and BLUE distance List
  final_list = r + b

  #all points should be +ve if all are correctly classified
  if all(i > 0 for i in final_list):
    return 'Yes'
  else:
    return 'No'

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [9]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def curve_smoothing(s):
  
    a=s.split(",")
    l=len(a)
    if a[0]=="_":
      # converting 3 cases into single case
        a[0]="0"  

    if a[l-1]=="_":
        a[l-1]="0"

    first=a[0]
    start=1

    for i in range(start,l):
        if a[i]!="_":
            k=i
            for j in range(start-1,k+1) :
                a[j]=(int(first)+int(a[i]))/int((k-start+2))
            start=k+1
            first=a[k]

    return a

S=  "_,_,30,_,_,_,50,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[10.0, 10.0, 12.0, 12.0, 12.0, 12.0, 4.0, 4.0, 4.0]


In [11]:
S=  "_,_,_,24"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[6.0, 6.0, 6.0, 6.0]


In [12]:
S=  "40,_,_,_,60"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[20.0, 20.0, 20.0, 20.0, 20.0]


In [13]:
S=  "80,_,_,_,_"
smoothed_values= curve_smoothing(S)
print(smoothed_values)

[16.0, 16.0, 16.0, 16.0, 16.0]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [ ]:
def compute_conditional_probabilites(a):
    f=[]
    s=[]
    m=[]
    for i in a:
        f.append(i[0])
        s.append((i[1]))
    
    #creatinf sets of F and S
    s=set(s)
    s=list(s)

    #creating dictionaries of F and S
    for k in f:
        for j in range (0,len(s)):
            m.append(k+s[j])
        mydict1 = {k:0 for k in m}
    
    for k in s:
        mydict2={k:0 for k in s}
    
    #https://stackoverflow.com/questions/57160252/find-conditional-probabilities-using-python
    for i in range(len(a)):
        k = a[i][0] + a[i][1]    
        mydict1[k] += 1          
        mydict2[a[i][1]] += 1
    

    for i in f:
        print("="*50)
        for j in s:
            print(f"probability of p(F={i}|S={j}) = {mydict1[str(i+j)]/mydict2[j]}")

a = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'], ['F4', 'S3'], ['F5', 'S1']]
compute_conditional_probabilites(a) 

probability of p(F=F1|S=S2) = 0.3333333333333333
probability of p(F=F1|S=S1) = 0.25
probability of p(F=F1|S=S3) = 0.0
probability of p(F=F2|S=S2) = 0.3333333333333333
probability of p(F=F2|S=S1) = 0.25
probability of p(F=F2|S=S3) = 0.3333333333333333
probability of p(F=F3|S=S2) = 0.3333333333333333
probability of p(F=F3|S=S1) = 0.0
probability of p(F=F3|S=S3) = 0.3333333333333333
probability of p(F=F1|S=S2) = 0.3333333333333333
probability of p(F=F1|S=S1) = 0.25
probability of p(F=F1|S=S3) = 0.0
probability of p(F=F2|S=S2) = 0.3333333333333333
probability of p(F=F2|S=S1) = 0.25
probability of p(F=F2|S=S3) = 0.3333333333333333
probability of p(F=F3|S=S2) = 0.3333333333333333
probability of p(F=F3|S=S1) = 0.0
probability of p(F=F3|S=S3) = 0.3333333333333333
probability of p(F=F2|S=S2) = 0.3333333333333333
probability of p(F=F2|S=S1) = 0.25
probability of p(F=F2|S=S3) = 0.3333333333333333
probability of p(F=F4|S=S2) = 0.0
probability of p(F=F4|S=S1) = 0.25
probability of p(F=F4|S=S3) = 0.

<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [19]:

def string_features(s1, s2):

    #getting unique words
    set1=set(s1.split())
    set2=set(s2.split())

    # a.Number of common words between S1, S2
    a=len(set1 & set2)

    # b. Words in S1 but not in S2
    b=list(set1 - set2)

    # c. Words in S2 but not in S1
    c=list(set2 - set1)

    return a,b,c

s1= "the first column F will contain only 5 uniques values"
s2= "the second column S will contain only 3 uniques values"
a,b,c=string_features(s1, s2)
print(a)
print(b)
print(c)

7
['5', 'F', 'first']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [18]:
from math import *

def compute_log_loss(A):
  sum=0
  n = len(A)
  for i in A:
    y = i[0]
    s = i[1]

    #loss for each point
    l = y*log10(s) + (1-y)*log10(1-s)
    sum+=l

  #overall loss
  loss = -1 * (sum/n)
  return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print('Loss = ',loss)

Loss =  0.42430993457031635
